function np = analyze_nonphysical(nu, G, K, ood_flag, cfg)
% ANALYZE_NONPHYSICAL — stratify non-physical flags against OOD.
%   Author: RCW (2026-06)

flag_nu = (nu < cfg.geomech.nu_range(1)) | (nu > cfg.geomech.nu_range(2));
flag_G  = G <= cfg.geomech.g_min;
flag_K  = K <= cfg.geomech.k_min;
flag_any = flag_nu | flag_G | flag_K;

n_total       = numel(flag_any);
n_ood         = sum(ood_flag);
n_non_ood     = sum(~ood_flag);
n_np_total    = sum(flag_any);
n_np_ood      = sum(flag_any & ood_flag);
n_np_non_ood  = sum(flag_any & ~ood_flag);

np.flag_nu       = flag_nu;
np.flag_G        = flag_G;
np.flag_K        = flag_K;
np.flag_any      = flag_any;

% Summary table rows: All / OOD / non-OOD
np.summary = table( ...
    {'All samples'; sprintf('OOD-flagged (|z|>%d)', cfg.deployment.ood_zthresh); ...
     'Non-OOD samples'}, ...
    [n_total; n_ood; n_non_ood], ...
    [sum(flag_nu); sum(flag_nu & ood_flag); sum(flag_nu & ~ood_flag)], ...
    [100*sum(flag_nu)/n_total; ...
     100*sum(flag_nu & ood_flag)/max(n_ood,1); ...
     100*sum(flag_nu & ~ood_flag)/max(n_non_ood,1)], ...
    [sum(flag_G); sum(flag_G & ood_flag); sum(flag_G & ~ood_flag)], ...
    [100*sum(flag_G)/n_total; ...
     100*sum(flag_G & ood_flag)/max(n_ood,1); ...
     100*sum(flag_G & ~ood_flag)/max(n_non_ood,1)], ...
    [sum(flag_K); sum(flag_K & ood_flag); sum(flag_K & ~ood_flag)], ...
    [100*sum(flag_K)/n_total; ...
     100*sum(flag_K & ood_flag)/max(n_ood,1); ...
     100*sum(flag_K & ~ood_flag)/max(n_non_ood,1)], ...
    [n_np_total; n_np_ood; n_np_non_ood], ...
    [100*n_np_total/n_total; ...
     100*n_np_ood/max(n_ood,1); ...
     100*n_np_non_ood/max(n_non_ood,1)], ...
    'VariableNames', {'Stratum','N','n_nu_out','pct_nu_out', ...
                      'n_G_neg','pct_G_neg','n_K_neg','pct_K_neg', ...
                      'n_any','pct_any'});

np.totals.n_total        = n_total;
np.totals.n_np_total     = n_np_total;
np.totals.n_np_ood       = n_np_ood;
np.totals.n_np_non_ood   = n_np_non_ood;
np.totals.silent_pct     = 100 * n_np_non_ood / max(n_np_total, 1);
end
